#!/bin/bash

# ensure /srv/pillar/auto_setup/ exists
# write pillar sls file with branch_tag and date_tag in it
# write new top.sls file containing it, 
# then everyone can get it from that sls file and pillar get

_usage() {
    echo ""
##    echo "usage: ${0}  [-h|--help] [-m|--minion <minion_to_use>] [ [-b|--branch <branch_to_build>] | [-t|--tag <tag>] ]"
    echo "usage: ${0}  [-h|--help] [-m|--minion <minion_to_use>] [-b|--branch <branch_to_build>]"
    echo ""
    echo "  -b, --branch    git HEAD of branch for specified major version, default 2016.11"
    echo "  -h, --help      this message"
    echo "  -m. --minion    salt-minion installed on salt-master node to use for code checkout, default 'm7m'"
##    echo "  -t, --tag       build's tag, e.g. v2016.11.1  for specific release version"
##     echo "  -v, --verbose   verbose output"
##     echo "  -d, --debug     debug output enabled"
##    echo "  -l, --log       logging mode"
    echo ""
    echo "  creates specified packages for major platforms, signed with Salt testing keys"
    echo "  dated by current start time of execution in YYYYMMDDhhmm format"
    echo "  current platforms:"
    echo "      Redhat 7 and 6"
    echo "      Debian 8 and 7"
    echo "      Raspbian"
    echo "      Ubuntu 16.04 and 14.04"
    echo ""
    echo "  script expects node to contain salt-master with auto_setup installed and"
    echo "  salt-minion installed on salt-master node, id 'm7m'"
    echo ""
}

vERBOSE=false
DEBUG=false
USAGE_HELP=false
LOG_MODE='debug'
RELEASE_TAG=''
RELEASE_BRANCH='2016.11'

## minion resident on Salt-Master node
CODE_MINION='m7m'

##    -v | --verbose ) VERBOSE=true; shift ;;
##    -d | --debug )  DEBUG=true; shift ;;
##    -l | --log )  LOG_MODE="$2"; shift 2 ;;
##    -t | --tag ) RELEASE_TAG="$2"; shift 2 ;;

## not validating input branch tag, format v2016.11.1 or 2016.11
BRANCH_TAG=''

while true; do
  case "${1}" in
    -b | --branch ) RELEASE_BRANCH="$2"; shift 2 ;;
    -h | --help ) USAGE_HELP=true; shift ;;
    -m | --minion ) CODE_MINION="$2"; shift 2 ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

## check if want help, display usage and exit
[[ ${USAGE_HELP} = 'false' ]] || {
  _usage
  exit 0
}


## input version tag overrides use of branch if present
[[ -z "${RELEASE_TAG}" ]] && BRANCH_TAG="${RELEASE_BRANCH}" || BRANCH_TAG="${RELEASE_TAG}"



##  MAIN BODY OF SCRIPT

## date tag is YearMontDayHourMinuteSecondMicrosecond aka jid
date_long=$(date +%Y%m%d%H%M%S%N)
curr_date="${date_long::-2}"

PILLAR_DIR='/srv/pillar'
PILLAR_AUTO_SETUP_DIR="auto_setup"
PILLAR_AUTO_SETUP_TAG_ABSFILE="${PILLAR_DIR}/${PILLAR_AUTO_SETUP_DIR}/tag_build_date.jinja"

if [[ ! -d "${PILLAR_DIR}/${PILLAR_AUTO_SETUP_DIR}" ]]; then
    echo "Missing vital directory ${PILLAR_DIR}/${PILLAR_AUTO_SETUP_DIR}, ensure system is correctly setup before proceeding"
    exit 1
fi

cat <<@EOF > "${PILLAR_AUTO_SETUP_TAG_ABSFILE}"
{% set branch_tag = '${BRANCH_TAG}' %}
{% set date_tag = '${curr_date}' %}
@EOF


salt ${CODE_MINION} saltutil.refresh_pillar
salt ${CODE_MINION} state.sls auto_setup

